In [7]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.6.0


In [11]:
t1 = tf.Variable([1,2,3]) # 변하는 숫자 model parameter
t2 = tf.constant([1,2,3]) # 변할 수 없음 

print(t1)
print(type(t1))
print(t2)
print(type(t2))

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [14]:
#numpy나 list를 tensor로 변환 가능
test_list = [1,2,3]
test_np = np.array([1,2,3])

t1 = tf.Variable(test_list)
t2 = tf.Variable(test_np)

print(t1)
print(type(t1))
print(t2)
print(type(t2))

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [12]:
test_list = [1,2,3]
test_np = np.array([1,2,3])

t1 = tf.constant(test_list)
t2 = tf.constant(test_np)

print(t1)
print(type(t1))
print(t2)
print(type(t2))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [16]:
t1 = tf.constant(test_list)
t2 = tf.Variable(test_list)
#t3 = tf.contant(t2) Variable를 constant로 바꿔주지 못한다.
t4 = tf.Variable(t1)  # constant를 Variable로 바꿔주는게 가능

In [21]:
# eager tensor를 만ㄷ는 다른 방법
t1 = tf.convert_to_tensor(test_list)
t2 = tf.convert_to_tensor(test_list)

t3 = tf.Variable(test_list)
t4 = tf.convert_to_tensor(t3) # 이걸로 하면 variable tensor도 변환 가능 foraward 기록이 없어짐

print(t1)
print(type(t1))
print(t2)
print(type(t2))
print(t3)
print(type(t3))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [23]:
test_list1 = [10,20,30]
test_list2 = [1,2,3]

t1 = tf.constant(test_list1)
t2 = tf.Variable(test_list2)

# constant랑 Variable을 더하면 eagertensor 나옴
t3 = t1 + t2 
print(type(t3))

# Variable 끼리 더해도 eagertensor가 나온다
t4 = t2 + t2
print(type(t4))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
