In [1]:
import tensorflow as tf
import numpy as np

In [3]:
t1 = tf.constant([1,2,3])
t2 = tf.constant([10,20,30])

In [6]:
print(t1 + t2) #각 원소바다 연산을 진행하게 된다 (shape이 맞아야함)
print(t1 - t2)
print(t1 * t2)
print(t1 / t2)
print(t1 % t2)
print(t1 // t2)

tf.Tensor([11 22 33], shape=(3,), dtype=int32)
tf.Tensor([ -9 -18 -27], shape=(3,), dtype=int32)
tf.Tensor([10 40 90], shape=(3,), dtype=int32)
tf.Tensor([0.1 0.1 0.1], shape=(3,), dtype=float64)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)


In [20]:
t1  = tf.random.normal(shape = (3,1), mean = 0, stddev = 5)
t2  = tf.random.normal(shape = (1,6), mean = 0, stddev = 5)

#  (3,5)  (2,7)  이렇게 완전 다르면 element wise 연산 불가능 !


In [21]:
t1 = tf.cast(t1, dtype = tf.int16)
t2 = tf.cast(t2, dtype = tf.int16)

In [22]:
print(t1.numpy())
print(t2.numpy())

[[5]
 [6]
 [6]]
[[ 2 -4  3 -1  4  1]]


In [23]:
t3 = t1 + t2 # shape이 다르면, 알아서 마춰서 연사늘 수행 해줌
print(t1)
print(t2)
print(t1 + t2)

tf.Tensor(
[[5]
 [6]
 [6]], shape=(3, 1), dtype=int16)
tf.Tensor([[ 2 -4  3 -1  4  1]], shape=(1, 6), dtype=int16)
tf.Tensor(
[[ 7  1  8  4  9  6]
 [ 8  2  9  5 10  7]
 [ 8  2  9  5 10  7]], shape=(3, 6), dtype=int16)


In [30]:
t1  = tf.random.normal(shape = (3,5, 7), mean = 0, stddev = 5)
t1 = tf.cast(t1, dtype = tf.int16)

print(t1.numpy())

[[[  5  -1   0  -1 -11   3  -2]
  [ 11   0   7   3  -2  -4   7]
  [  1   1   3  -2  -3  -4  -8]
  [ -5   1  -5  -5  -4   6   0]
  [ -2  -2   0  -4  -1  -8  -7]]

 [[  2   1   0  -1 -10   6  -1]
  [  0  -4  -5   5   1   1  -3]
  [ -9  -4   3  -8   0  -1   0]
  [ -4  11   8  -2   0   1   4]
  [ -1   1  -6 -12  -5  -4   1]]

 [[  3   7   2   0   2   1   0]
  [  0   2   0  -1   9   0   6]
  [ -3   3  -3 -12  -2  -8  -4]
  [ -8  -1  -3   0  -5   3   2]
  [  2  -5  -2  -6  10   8  -2]]]


tf.reduce_sum   그냥 모든 합 ,  
tf.reduce_prod
tf.reduce_max
tf.reduce_min
tf.reduce_mean
tf.reduce_std
tf.reduce_variance
tf.reduce_all
tf.reduce_any

(3, 4)   axis = 1 이면,  4 축을 없애면서 더해주기 -> (3. 0) 만 남는다.

축 없으면 그냥 다 더해 주기, axis 설정 -> 축 설정  axis = 0  세로 반향 , axis = 1 가로 방향

In [32]:
print(t1.shape)
t2 = tf.reduce_sum(t1, axis = 0 )
print(t2.shape)
t2 = tf.reduce_sum(t1, axis = 1 )
print(t2.shape)
t2 = tf.reduce_sum(t1, axis = 2 )
print(t2.shape)




(3, 5, 7)
(5, 7)
(3, 7)
(3, 5)
